server:
  port: 8082

spring:
  application:
    name: service-provide
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 5s
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}